### ISSUE TITLE
Firefox browser crash when clicking right arrow on chord tooltips

### ISSUE THREAD

**Issue by j-zhao** [music-markdown/music-markdown#119]
https://music-markdown.github.io/#/repos/music-markdown/almost-in-time/viewer/master/A%20Thousand%20Years%20-%20Christina%20Perri.md

User navigated to link above, clicked on right arrow while hovering over the last "D" chord, crashes browser.

I am unable to personally reproduce it, investigating.

**Comment by shadanan** [comment]
Closing as this seems old and may no longer be relevant.
