### ISSUE TITLE
Github access token should be configured at a owner/repo level, rather than global

### ISSUE THREAD

**Issue by j-zhao** [music-markdown/music-markdown#130]
Given that a user should be able to add/modify contents in their own repo, browser console probably isn't the best way to pass in an access token.  Users should be able to modify/update their access tokens, and this should be configured at an owner/repo level. Currently, a token is global under `localStorage.setItem('music-markdown:github_token', <token>)`.

**Comment by shadanan** [comment]
Most users only have one github account. This is a use case that seems both unlikely, and solvable using different browser accounts.
