### ISSUE TITLE
Chord diagrams render outside of the display

### ISSUE THREAD

**Issue by Inkomidwastaken** [music-markdown/music-markdown#192]
Chord Diagrams are always displayed exactly above the written chord.
When the chord ist near the top or the side of the website the Chord Diagrams is cut of.

It would also be nice to have Chord Diagrams that are always displayed.

**Comment by shadanan** [comment]
I've been meaning to fix this known problem for a very long while. I think if we replace the current custom logic with something like popper.js, it can be fixed relatively easily. I'll take a look.
